###############################################################################
## Fichier de description du package pour Anaconda.org
## Attention, les chaines PYPI_VERSION, PYPI_URL et PYPI_SHA256 sont remplacées
## par la CI, il faut les conserver.
###############################################################################

{% set name = "OpenFisca-France" %}
{% set version = "PYPI_VERSION" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.9,<4.0
    - OpenFisca-Core >=40,<41


test:
  imports:
    - openfisca_france
  requires:
    - pip
  commands:
    - pip check

outputs:
  - name: openfisca-france

  - name: openfisca-france-scipy
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - scipy >= 1.10.1, < 2.0
        - {{ pin_subpackage('openfisca-france', exact=True) }}

  - name: openfisca-france-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >= 2.0.2, < 3.0
        - flake8 >= 6.0.0, < 7.0.0
        - flake8-print >= 5.0.0, < 6.0.0
        - flake8-quotes >= 3.3.2
        - pytest >= 7.2.2, < 8.0
        - requests >=2.8
        - yamllint >=1.11.1,<1.27
        - {{ pin_subpackage('openfisca-france-scipy', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE.AGPL.txt
  summary: "French tax and benefit system for OpenFisca"
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the OpenFisca model of the French tax and benefit system.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-france/
